### ISSUE TITLE
How to add DNS entries with rancher

### ISSUE THREAD

**Issue by N1v0k** [digitalLumberjack/docker-bind9#1]
How can I automatically add DNS entries when deployed as environment service in rancher?
There is no vim, vi or nano in the container so I also can't add anything manually?

**Comment by digitalLumberjack** [comment]
Hi sorry for the late answer.
You can use nsupdate to create manually new entries in the bind9 zones : https://linux.die.net/man/8/nsupdate

**Comment by digitalLumberjack** [comment]
Annnnd you can use the rfc2136 dns update service in rancher (https://github.com/rancher/community-catalog/tree/master/templates/dnsupdate-rfc2136)  to have the bind9 automatically updated with services fqdn.

**Comment by N1v0k** [comment]
Hi,

thanks for your answer, I already figured out how to use ith with RFC2136 DNS Updater and it works perfectly!

Thanks and a happy new year!
